### ISSUE TITLE
Add README and Templates

### ISSUE THREAD

**Issue by titaniumbones** [datatogether/research#14]
Make sure this repo has the following files:
- [x] Readme `README.md`
   - [x] Repo Badges for: Github Project, Slack, License
   - [x] 1-3 sentence description of repository contents
   - [x] Getting Involved section
- [x] License -- `LICENSE`
- [x] Contributing Guidelines (minimal and pointing to org-wide) `.github/CONTRIBUTING.md`
- [x] Issue Template -- `.github/ISSUE_TEMPLATE.md`
- [x] GitHub Description from 1-3 sentence readme blurb

This issue forms part of [a project-wide meta-issue](https://github.com/datatogether/roadmap/issues/37)

**Comment by dcwalk** [comment]
This is done 🎉
