### ISSUE TITLE
Is this the place for other decentralized projects?

### ISSUE THREAD

**Issue by dcwalk** [datatogether/research#18]
Hey there, thank you for submitting an issue!

We are trying to keep issues for feature requests and bug reports. Please
complete the following checklist before creating a new one:

- [x] feature request

---
I'd love to bring over some of the projects listed here https://github.com/datatogether/datatogether/issues/3:

```
- indie web
- network commons (e.g. mesh nets, netCommons, commons-based licensing https://wiki.p2pfoundation.net/Network_Commons_License)
- p2p foundation
- digital justice / data justice / design justice 
    - https://civicquarterly.com/article/two-way-streets/
    - https://datajustice.github.io/report/
    - ttp://detroitdjc.org/
- community technology
    - http://detroitcommunitytech.org/learning-materials
```

**Comment by b5** [comment]
Oooh I think that's a great idea, and totally think they belong here. thoughts @mhucka?

**Comment by dcwalk** [comment]
Hey! This has been sitting open for awhile. I think we can sit on it given the direction this repo and DT stuff is going. I'm gonna close :3
