### ISSUE TITLE
Add BioFabric viz to docs

### ISSUE THREAD

**Issue by patcon** [datatogether/research#2]
Don't wanna step on toes with edits, but don't wanna forget!

http://www.biofabric.org/gallery/pages/SuperQuickBioFabric.html

cc: @shaqsingh @b5

**Comment by b5** [comment]
No toes to be stepped on, feel free to jump in with a PR, otherwise I'll step to it tomorrow morn!

**Comment by mhucka** [comment]
@patcon Since I was already editing the document today, I went ahead and added mention of BioFabric to the revised document, in commit [b747b7d5315827aa85f2a390679004bd5011e566](https://github.com/archivers-space/research/commit/b747b7d5315827aa85f2a390679004bd5011e566)

**Comment by mhucka** [comment]
I will close this issue in a day or two, if no further items come up.

**Comment by mhucka** [comment]
Woops, I originally misread the thread in Slack and now I see that @shaqsingh was the one who originally pointed out biofabric, not @patcon. I edited the commit message to assign credit correctly now. Sorry!
